name: Build & Upload Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install deps
        run: npm install

      - name: Build web
        run: npm run build

      - name: Add/Sync Android
        run: |
          npx --yes @capacitor/cli@5 add android || true
          npx --yes @capacitor/cli@5 sync android

      - name: Ensure manifest permissions (Internet, location, notifications, FGS)
        run: |
          FILE="android/app/src/main/AndroidManifest.xml"

          ensure_perm() {
          P=$1
          grep -q "android.permission.${P}" "$FILE" || \
          sed -i "s#</manifest>#  <uses-permission android:name=\"android.permission.${P}\" />\n</manifest>#g" "$FILE"
          }

          ensure_perm INTERNET
          ensure_perm ACCESS_COARSE_LOCATION
          ensure_perm ACCESS_FINE_LOCATION
          ensure_perm ACCESS_BACKGROUND_LOCATION
          ensure_perm FOREGROUND_SERVICE
          ensure_perm FOREGROUND_SERVICE_LOCATION
          ensure_perm WAKE_LOCK
          
    # Android 13+ meldingen
    
          ensure_perm POST_NOTIFICATIONS

    # Sommige OEMs vereisen boot-complete om op te starten (we gebruiken het niet actief, maar schaadt niet)
    
          ensure_perm RECEIVE_BOOT_COMPLETED


      # Plugin-compat stubs (anders compile error op AGP 8)
      - name: Patch BG plugin BuildConfig stubs
        run: |
          PLUG="node_modules/@capacitor-community/background-geolocation/android/src/main/java/com/equimaps/capacitor_background_geolocation"
          mkdir -p "$PLUG"
          cat > "$PLUG/BuildConfig.java" <<'EOF'
          package com.equimaps.capacitor_background_geolocation;
          public final class BuildConfig { public static final boolean DEBUG = false; }
          EOF
          CAP="node_modules/@capacitor-community/background-geolocation/android/src/main/java/com/getcapacitor/android"
          mkdir -p "$CAP"
          cat > "$CAP/BuildConfig.java" <<'EOF'
          package com.getcapacitor.android;
          public final class BuildConfig { public static final boolean DEBUG = false; }
          EOF

      - name: Make gradle executable
        run: chmod +x android/gradlew || true

      - name: Build APK (debug)
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: DispatchTracking-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
